services:
  - type: web
    name: homiee-ml-service
    runtime: python
    plan: free
    rootDir: ml-service
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_ENV
        value: production
      - key: LOG_LEVEL
        value: INFO
