services:
  - type: web
    name: homiee-ml-service
    runtime: python
    plan: free
    rootDir: ml-service
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir --prefer-binary --only-binary=numpy,pandas,scikit-learn -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app --timeout 120 --workers 1 --max-requests 1000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_ENV
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONUNBUFFERED
        value: "1"
